- name: Add bingo key
  apt_key:
    id: "EA312927"
    keyserver: keyserver.ubuntu.com
  tags: install

- name: add bongo repo
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
  tags: install

- name: Install bingo-bongo
  apt:
    name: mongodb-org
    state: present
  tags: install

- name: Enable bongo-bingo
  systemd:
    name: mongod
    enabled: yes
    state: started
  tags: install
